# config
[config]
skip_core_tasks = true
# update
## `./CREDITS`
[tasks."update.credits"]
description = "update `./CREDITS`"
script = '''
gocredits -skip-missing . > ./CREDITS
'''
## mocks
[tasks."update.mocks"]
description = "update mocks"
script = '''
# ./app
mockgen -source=./app/domain/mindnum/mindnum_repository.go -destination=./app/domain/mindnum/mindnum_repository_mock.go -package=mindnum
# ./pkg
mockgen -source=./pkg/proxy/buffer.go -destination=./pkg/proxy/buffer_mock.go -package=proxy
mockgen -source=./pkg/proxy/cobra.go -destination=./pkg/proxy/cobra_mock.go -package=proxy
mockgen -source=./pkg/proxy/debug.go -destination=./pkg/proxy/debug_mock.go -package=proxy
mockgen -source=./pkg/proxy/os.go -destination=./pkg/proxy/os_mock.go -package=proxy
mockgen -source=./pkg/proxy/pflag.go -destination=./pkg/proxy/pflag_mock.go -package=proxy
'''

# test
[tasks."test"]
description = "execute tests"
script = '''
# execute tests
go test -v -p 1 ./... -cover -coverprofile=./cover.out
# remove proxies and mocks from coverage report
awk '!/(proxy|_mock)/' ./cover.out > temp_cover.out && mv temp_cover.out cover.out
# generate HTML report
go tool cover -html=./cover.out -o ./docs/coverage.html
# clean up
rm ./cover.out
'''
